spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shipment
    username: odyildiz
    password: pswrd
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    org.springframework.data : debug