version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.6.5-management
    volumes:
      - ./data:/var/lib/rabbitmq:rw
      - ./definitions.json:/opt/definitions.json:ro
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:13.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: odyildiz
      POSTGRES_PASSWORD: pswrd
      POSTGRES_DB: shipment
    volumes:
      - ./create_shipment_outbox_table.sql:/docker-entrypoint-initdb.d/create_shipment_outbox_table.sql
